# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6157be5eb6f8ae01895477fdf870582858200b8d41f0f3145ad88fd286f0b99da12ab7e1ba9cffa1a838d03eee6d3fac7a552efef1314c456066ccb49d854351

test:
  secret_key_base: 01a10cec9b42f5fc03197c88352281ae84e9e300ceed942bc4818fe51f33285cb5af2891542e616f7738e7b02e39f105954a20e3c3e112b65f096aea79d283e3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
